### ISSUE TITLE
`yarn dev` says "path argument must be of type string"

### ISSUE THREAD

**Issue by canadaduane** [baileyherbert/svelte-webpack-starter#5]
When I do a clean checkout & run `yarn && yarn dev` (after workaround #4), I get the following error:

```
$ yarn dev

yarn run v1.23.0-0
$ webpack serve
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /build/
ℹ ｢wds｣: Content not from webpack is served from public
ℹ ｢wdm｣: Failed to compile.
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.dirname (path.js:1128:5)
    at WatcherManager.watchFile (/Users/duane/Relm/relm-wp5/node_modules/watchpack/lib/getWatcherManager.js:30:26)
    at /Users/duane/Relm/relm-wp5/node_modules/watchpack/lib/watchpack.js:231:41
    at Object.exports.batch (/Users/duane/Relm/relm-wp5/node_modules/watchpack/lib/watchEventSource.js:326:3)
    at Watchpack.watch (/Users/duane/Relm/relm-wp5/node_modules/watchpack/lib/watchpack.js:229:20)
    at NodeWatchFileSystem.watch (/Users/duane/Relm/relm-wp5/node_modules/webpack/lib/node/NodeWatchFileSystem.js:84:16)
    at Watching.watch (/Users/duane/Relm/relm-wp5/node_modules/webpack/lib/Watching.js:238:48)
    at /Users/duane/Relm/relm-wp5/node_modules/webpack/lib/Watching.js:215:13
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm not sure what to check for here. It seems the watcher is being passed an undefined path?

**Comment by baileyherbert** [comment]
I'm able to see this too, but only with `yarn`. Everything is normal with `npm` and `pnpm`.

I determined from #4 that yarn is installing dependencies differently than npm which is causing inconsistencies. This is probably the same case. I'll look deeper into this when I have a chance tonight.

**Comment by canadaduane** [comment]
So it looks like this is caused indirectly by another error:

I noticed when debugging `compilation.fileDependencies` that there is a large array of files followed by a single `[..., null]` entry at the end. Looking further, using `webpack serve --stats verbose` I found this error:

```
ERROR in ./src/App.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
Error: PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/duane/Relm/relm-wp5/node_modules/postcss/lib/processor.es6:117:15)
    at new Processor (/Users/duane/Relm/relm-wp5/node_modules/postcss/lib/processor.es6:38:25)
    at Object.postcss (/Users/duane/Relm/relm-wp5/node_modules/postcss/lib/postcss.es6:34:10)
    at process (/Users/duane/Relm/relm-wp5/node_modules/svelte-preprocess/dist/transformers/postcss.js:28:59)
    at transformer (/Users/duane/Relm/relm-wp5/node_modules/svelte-preprocess/dist/transformers/postcss.js:72:16)
    at Object.transform (/Users/duane/Relm/relm-wp5/node_modules/svelte-preprocess/dist/autoProcess.js:37:12)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processImmediate (internal/timers.js:434:9)
    at style (/Users/duane/Relm/relm-wp5/node_modules/svelte-preprocess/dist/autoProcess.js:167:37)
    at process_single_tag (/Users/duane/Relm/relm-wp5/node_modules/svelte/src/compiler/preprocess/index.ts:160:21)
```

When I add `yarn add -D postcss@8.1` and then `yarn remove optimize-css-assets-webpack-plugin` (and remove references to `OptimizeCSSAssetsPlugin` in webpack.config.js) then everything "works". Of course, this solution causes the CSS minification in prod build to be disabled, however.

**Comment by edwardrubio** [comment]
#6 seems to fix this issue on my end, I'm still pretty new to svelte so I could be wrong.

**Comment by baileyherbert** [comment]
Thanks @edwardrubio, your PR did fix this. The issue would have been peer dependencies defined in `optimize-css-assets-webpack-plugin`. I'm going to explicitly add `postcss` to the dev dependencies to prevent the issue from reoccurring in the future.
