### ISSUE TITLE
Declarations not found

### ISSUE THREAD

**Issue by lukasdiegelmann** [baileyherbert/svelte-webpack-starter#9]
Hey,
I cannot figure out what went wrong, but I receive an error when importing any file.

this is what I get:
```
Failed to init component
<App>
ReferenceError: Auth is not defined
    at create_fragment (http://localhost:8080/build/bundle.js:11463:2)
    at init (http://localhost:8080/build/bundle.js:13891:37)
    at new App (http://localhost:8080/build/bundle.js:11550:56)
    at createProxiedComponent (http://localhost:8080/build/bundle.js:11420:9)
    at new ProxyComponent (http://localhost:8080/build/bundle.js:10985:92)
    at new Proxy<App> (http://localhost:8080/build/bundle.js:11085:11)
    at Object../src/main.ts (http://localhost:8080/build/bundle.js:14146:13)
    at __webpack_require__ (http://localhost:8080/build/bundle.js:14213:33)
    at http://localhost:8080/build/bundle.js:15355:11
    at http://localhost:8080/build/bundle.js:15359:12
```

Maybe you have an idea of what went wrong?

**Comment by baileyherbert** [comment]
Ah, that's my mistake. Remove this line from the top of `tsconfig.json`:

```json
    "module": "commonjs",
```

**Comment by lukasdiegelmann** [comment]
It still does not work. Getting the same error.

This is my `tsconfig.json`:
```
{
    "module": "commonjs",
    "include": ["src/**/*", "webpack.config.ts"],
    "exclude": ["node_modules/*", "__sapper__/*", "public/*"],
    "compilerOptions": {
        "moduleResolution": "node",
        "target": "es2017",
        "module": "commonjs",
        "importsNotUsedAsValues": "remove",
        "isolatedModules": true,
        "esModuleInterop": true,
        "sourceMap": true,
        "strict": false,
        "baseUrl": ".",
        "paths": {
            "src/*": ["src/*"]
        },
        "types": [
            "svelte",
            "svelte/store",
            "svelte/motion",
            "svelte/transition",
            "svelte/animate",
            "svelte/easing"
        ]
    },

    // Fixes errors when changing `module` to ES in the above compiler options
    // See: https://github.com/webpack/webpack-cli/issues/2458#issuecomment-846635277
    "ts-node": {
        "compilerOptions": {
            "module": "commonjs"
        }
    }
}

```

**Comment by baileyherbert** [comment]
Can you copy/paste the `tsconfig.json` from here and see if it works?
https://github.com/baileyherbert/svelte-webpack-starter/blob/master/tsconfig.json

**Comment by lukasdiegelmann** [comment]
Yes, it works now. Really appreciate your help!
